[package]
name = "brainfuck_interpreter"
version = "0.1.0"
edition = "2021"
authors = ["BastaMasta <bastamasta3150@proton.me>"]
description = "A simple BrainFuck interpreter made by me, in Rust!"


[dependencies]
